server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/hospital_mt
    username: postgres
    password: 2005
    driver-class-name: org.postgresql.Driver

  jpa:
    properties:
      hibernate:
        multiTenancy: SCHEMA
        tenant_identifier_resolver: com.zaalima.hospital.tenant.CurrentTenantIdentifierResolverImpl
        multi_tenant_connection_provider: com.zaalima.hospital.tenant.SchemaMultiTenantConnectionProvider
        ddl-auto: update
        show-sql: true
        format_sql: true
  
logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE

      

        
