spring.application.name=hospital-backend
# Master DB (holds tenant metadata)
spring.datasource.url=jdbc:postgresql://localhost:5432/hospital_mt
spring.datasource.username=postgres
spring.datasource.password=2005
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.open-in-view=false

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
logging.level.org.hibernate.SQL=DEBUG

